
# Chinese menus

[[docs]]
  name = "技术公益"
  weight = 1
  # identifier = "about"
  url = "/zh/about/intro"

[[docs]]
  name = "团队协作"
  weight = 5
  identifier = "getting-started"
  url = "/zh/about/teamwork"

[[docs]]
  name = "公益成果"
  weight = 15
  identifier = "themes"
  #url = "/zh/about/achievement"
  url = "/zh/about/todo"

[[docs]]
  name = "数据安全"
  weight = 15
  identifier = "themes"
  post = "break"
  #url = "/zh/about/achievement"
  url = "/zh/about/security"

# Core languages.zh.menus

[[docs]]
  name = "组织架构"
  weight = 20
  #identifier = "content-management"
  #post = "expanded"
  url = "/zh/about/todo"

[[docs]]
  name = "产品组"
  weight = 25
  #identifier = "templates"
  url = "/zh/about/pm"

[[docs]]
  name = "设计组"
  weight = 26
  #identifier = "functions"
  url = "/zh/about/todo"

[[docs]]
  name = "开发组"
  weight = 27
  #identifier = "variables"
  url = "/zh/about/todo"

[[docs]]
  name = "运维组"
  weight = 29
  #identifier = "variables"
  url = "/zh/about/todo"

[[docs]]
  name = "运营组"
  weight = 30
  #identifier = "variables"
  url = "/zh/about/todo"
 
[[docs]]
  name = "后勤组"
  weight = 35
  #identifier = "variables"
  url = "/zh/about/todo" 

[[docs]]
  name = "兴趣组"
  weight = 40
  post = "break"
  #identifier = "commands"
  url = "/zh/about/interest"



# LOW LEVEL ITEMS
[[docs]]
  name = "团队文化"
  weight = 70
  identifier = "tools"
  url = "/zh/about/todo"

[[docs]]
  name = "团队理念"
  weight = 80
  identifier = "hosting-and-deployment"
  url = "/zh/about/todo"

[[docs]]
  name = "加入我们"
  weight = 100
  post = "break"
  identifier = "contribute"
  #url = "/zh/about/contribute"
  url = "/zh/about/todo"

[[global]]
  name = "公益新闻"
  weight = 1
  identifier = "news"
  url = "/zh/news/"

[[global]]
  name = "团队介绍"
  weight = 5
  identifier = "docs"
  url = "/zh/about/"

[[global]]
  name = "开发环境"
  weight = 10
  identifier = "themes"
  url = "/zh/dev/"

[[global]]
  name = "成果展示"
  weight = 20
  identifier = "showcase"
  url = "/zh/showcase/"

# Anything with a weight > 100 gets an external icon
[[global]]
  name = "社区"
  weight = 150
  icon = true
  identifier = "community"
  post = "external"
  url = "https://bbs.airdb.net/"

[[global]]
  name = "GitHub"
  weight = 200
  identifier = "github"
  post = "external"
  url = "https://github.com/airdb"
